version: 2.1

orbs:
  windows: circleci/windows@2.4.0

jobs:
  build:  
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Build
          command: |
            dotnet build
            

workflows:
  build: 
    jobs:
      - build
